use Haze_Vape_DB;

DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS gear;
DROP TABLE IF EXISTS juice;
DROP TABLE IF EXISTS mods;
DROP TABLE IF EXISTS tanks;

DROP TABLE IF EXISTS roles;


CREATE TABLE roles (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  role_id INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (role_id) REFERENCES roles (id)
);

-- MERCH






CREATE TABLE gear (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  price DECIMAL(3, 2) NOT NULL
  stock_id INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id)
);



DROP TABLE IF EXISTS clothes;
CREATE TABLE clothes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  brand VARCHAR(255) NOT NULL,
  price DECIMAL(6, 4) NOT NULL,
  size VARCHAR(100) NOT NULL,
  stock_id INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id)
);


CREATE TABLE juice (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  brand VARCHAR(100) NOT NULL,
  title VARCHAR(255) NOT NULL,
  ml int(3) NOT NULL,
  price DECIMAL(2, 2) NOT NULL,
  mg VARCHAR(10),
  stock_id INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE mods (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  brand VARCHAR(100) NOT NULL,
  title VARCHAR(255) NOT NULL,
  size int(3) NOT NULL,
  price DECIMAL(3, 2) NOT NULL,
  batteries VARCHAR(59),
  stock_id INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE tanks (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  brand VARCHAR(100) NOT NULL,
  title VARCHAR(255) NOT NULL,
  size int(3) NOT NULL,
  price DECIMAL(3, 2) NOT NULL,
  stock_id INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id)
);