use Haze_Vape_DB;



DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE IF NOT EXISTS roles (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  role_id INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (role_id) REFERENCES roles (id)

);


CREATE TABLE IF NOT EXISTS products(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  brand VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  discription VARCHAR(500),
  price DECIMAL(6, 4) NOT NULL,
  size VARCHAR(255),
  mg INT(3),
  ml INT(3),
  batteries VARCHAR(255)

);

